services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  fastapi:
    build: ./back-fastapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@postgres:5432/mydb
    depends_on:
      - postgres
    networks:
      - app-network

  vite-react:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://localhost:8000
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge