[tool.poetry]
name = "back-fastapi"
version = "0.1.0"
description = ""
authors = ["3AlblA3 <alexandreblanc22@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.118.0"
uvicorn = "^0.37.0"
sqlalchemy = "^2.0.0"
psycopg2-binary = "^2.9.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
